package com.globalhitss.miingresohitss.model;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Descuento generated by hbm2java
 */
@Entity
@Table(name = "DESCUENTO", schema = "MIINGRESOHITSS")
public class Descuento implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idDescuento;
	private Producto producto;
	private BigDecimal porcentaje;
	private Date fechaInicial;
	private Date fechaFinal;

	public Descuento() {
	}

	public Descuento(BigDecimal idDescuento, Producto producto, Date fechaInicial) {
		this.idDescuento = idDescuento;
		this.producto = producto;
		this.fechaInicial = fechaInicial;
	}

	public Descuento(BigDecimal idDescuento, Producto producto, BigDecimal porcentaje, Date fechaInicial,
			Date fechaFinal) {
		this.idDescuento = idDescuento;
		this.producto = producto;
		this.porcentaje = porcentaje;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_DESCUENTO")
        @SequenceGenerator(name = "ID_DESCUENTO", sequenceName = "ID_DESCUENTO", allocationSize = 1, initialValue = 1)
	@Column(name = "ID_DESCUENTO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDescuento() {
		return this.idDescuento;
	}

	public void setIdDescuento(BigDecimal idDescuento) {
		this.idDescuento = idDescuento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "PORCENTAJE", precision = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIAL", nullable = false, length = 7)
	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FINAL", length = 7)
	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

}
