package com.globalhitss.miingresohitss.model;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DetalleVenta generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_VENTA", schema = "MIINGRESOHITSS")
public class DetalleVenta implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idDetalleVenta;
	private Producto producto;
	private Venta venta;
	private BigDecimal valorUnitario;
	private BigDecimal cantidadVenta;

	public DetalleVenta() {
	}

	public DetalleVenta(BigDecimal idDetalleVenta, Producto producto, Venta venta, BigDecimal valorUnitario,
			BigDecimal cantidadVenta) {
		this.idDetalleVenta = idDetalleVenta;
		this.producto = producto;
		this.venta = venta;
		this.valorUnitario = valorUnitario;
		this.cantidadVenta = cantidadVenta;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_DETALLE_VENTA")
        @SequenceGenerator(name = "ID_DETALLE_VENTA", sequenceName = "ID_DETALLE_VENTA", allocationSize = 1, initialValue = 1)
	@Column(name = "ID_DETALLE_VENTA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDetalleVenta() {
		return this.idDetalleVenta;
	}

	public void setIdDetalleVenta(BigDecimal idDetalleVenta) {
		this.idDetalleVenta = idDetalleVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_VENTA", nullable = false)
	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	@Column(name = "VALOR_UNITARIO", nullable = false, precision = 18)
	public BigDecimal getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@Column(name = "CANTIDAD_VENTA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCantidadVenta() {
		return this.cantidadVenta;
	}

	public void setCantidadVenta(BigDecimal cantidadVenta) {
		this.cantidadVenta = cantidadVenta;
	}

}
