package com.globalhitss.miingresohitss.model;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "INVENTARIO", schema = "MIINGRESOHITSS")
public class Inventario implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idInventario;
	private Bodega bodega;
	private Producto producto;
	private BigDecimal cantidadDisponible;

	public Inventario() {
	}

	public Inventario(BigDecimal idInventario, Bodega bodega, Producto producto, BigDecimal cantidadDisponible) {
		this.idInventario = idInventario;
		this.bodega = bodega;
		this.producto = producto;
		this.cantidadDisponible = cantidadDisponible;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_INVENTARIO")
        @SequenceGenerator(name = "ID_INVENTARIO", sequenceName = "ID_INVENTARIO", allocationSize = 1, initialValue = 1)
	@Column(name = "ID_INVENTARIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdInventario() {
		return this.idInventario;
	}

	public void setIdInventario(BigDecimal idInventario) {
		this.idInventario = idInventario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_BODEGA", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "CANTIDAD_DISPONIBLE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCantidadDisponible() {
		return this.cantidadDisponible;
	}

	public void setCantidadDisponible(BigDecimal cantidadDisponible) {
		this.cantidadDisponible = cantidadDisponible;
	}

}
