package com.globalhitss.miingresohitss.model;
// Generated 7/05/2020 01:09:22 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTO", schema = "MIINGRESOHITSS")
public class Producto implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idProducto;
	private String nombreProducto;
	private String descripcionProducto;
	private String fotoProducto;
	private String unidadMedida;
	private BigDecimal mesesGarantia;
	private String fabricante;
	private String estadoProducto;
	private BigDecimal precioMinimo;
	private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);
	private Set<Descuento> descuentos = new HashSet<Descuento>(0);
	private Set<Inventario> inventarios = new HashSet<Inventario>(0);

	public Producto() {
	}

	public Producto(BigDecimal idProducto, String nombreProducto, String unidadMedida, String fabricante,
			String estadoProducto, BigDecimal precioMinimo) {
		this.idProducto = idProducto;
		this.nombreProducto = nombreProducto;
		this.unidadMedida = unidadMedida;
		this.fabricante = fabricante;
		this.estadoProducto = estadoProducto;
		this.precioMinimo = precioMinimo;
	}

	public Producto(BigDecimal idProducto, String nombreProducto, String descripcionProducto, String fotoProducto,
			String unidadMedida, BigDecimal mesesGarantia, String fabricante, String estadoProducto,
			BigDecimal precioMinimo, Set<DetalleVenta> detalleVentas, Set<Descuento> descuentos,
			Set<Inventario> inventarios) {
		this.idProducto = idProducto;
		this.nombreProducto = nombreProducto;
		this.descripcionProducto = descripcionProducto;
		this.fotoProducto = fotoProducto;
		this.unidadMedida = unidadMedida;
		this.mesesGarantia = mesesGarantia;
		this.fabricante = fabricante;
		this.estadoProducto = estadoProducto;
		this.precioMinimo = precioMinimo;
		this.detalleVentas = detalleVentas;
		this.descuentos = descuentos;
		this.inventarios = inventarios;
	}

	@Id

	@Column(name = "ID_PRODUCTO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(BigDecimal idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "NOMBRE_PRODUCTO", nullable = false, length = 20)
	public String getNombreProducto() {
		return this.nombreProducto;
	}

	public void setNombreProducto(String nombreProducto) {
		this.nombreProducto = nombreProducto;
	}

	@Column(name = "DESCRIPCION_PRODUCTO", length = 100)
	public String getDescripcionProducto() {
		return this.descripcionProducto;
	}

	public void setDescripcionProducto(String descripcionProducto) {
		this.descripcionProducto = descripcionProducto;
	}

	@Column(name = "FOTO_PRODUCTO", length = 200)
	public String getFotoProducto() {
		return this.fotoProducto;
	}

	public void setFotoProducto(String fotoProducto) {
		this.fotoProducto = fotoProducto;
	}

	@Column(name = "UNIDAD_MEDIDA", nullable = false, length = 10)
	public String getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	@Column(name = "MESES_GARANTIA", precision = 22, scale = 0)
	public BigDecimal getMesesGarantia() {
		return this.mesesGarantia;
	}

	public void setMesesGarantia(BigDecimal mesesGarantia) {
		this.mesesGarantia = mesesGarantia;
	}

	@Column(name = "FABRICANTE", nullable = false, length = 50)
	public String getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(String fabricante) {
		this.fabricante = fabricante;
	}

	@Column(name = "ESTADO_PRODUCTO", nullable = false, length = 3)
	public String getEstadoProducto() {
		return this.estadoProducto;
	}

	public void setEstadoProducto(String estadoProducto) {
		this.estadoProducto = estadoProducto;
	}

	@Column(name = "PRECIO_MINIMO", nullable = false, precision = 18)
	public BigDecimal getPrecioMinimo() {
		return this.precioMinimo;
	}

	public void setPrecioMinimo(BigDecimal precioMinimo) {
		this.precioMinimo = precioMinimo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<DetalleVenta> getDetalleVentas() {
		return this.detalleVentas;
	}

	public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
		this.detalleVentas = detalleVentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Descuento> getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(Set<Descuento> descuentos) {
		this.descuentos = descuentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Inventario> getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set<Inventario> inventarios) {
		this.inventarios = inventarios;
	}

}
