package com.globalhitss.miingresohitss.model;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name = "VENTA", schema = "MIINGRESOHITSS")
public class Venta implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idVenta;
	private Cliente cliente;
	private MedioPago medioPago;
	private Date fechaVenta;
	private String estadoVenta;
	private BigDecimal valorTotal;
        @JsonIgnore
	private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);

	public Venta() {
	}

	public Venta(BigDecimal idVenta, Cliente cliente, MedioPago medioPago, Date fechaVenta, String estadoVenta,
			BigDecimal valorTotal) {
		this.idVenta = idVenta;
		this.cliente = cliente;
		this.medioPago = medioPago;
		this.fechaVenta = fechaVenta;
		this.estadoVenta = estadoVenta;
		this.valorTotal = valorTotal;
	}

	public Venta(BigDecimal idVenta, Cliente cliente, MedioPago medioPago, Date fechaVenta, String estadoVenta,
			BigDecimal valorTotal, Set<DetalleVenta> detalleVentas) {
		this.idVenta = idVenta;
		this.cliente = cliente;
		this.medioPago = medioPago;
		this.fechaVenta = fechaVenta;
		this.estadoVenta = estadoVenta;
		this.valorTotal = valorTotal;
		this.detalleVentas = detalleVentas;
	}

	@Id
        @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_VENTA")
        @SequenceGenerator(name = "ID_VENTA", sequenceName = "ID_VENTA", allocationSize = 1, initialValue = 1)
	@Column(name = "ID_VENTA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(BigDecimal idVenta) {
		this.idVenta = idVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MEDIO_PAGO", nullable = false)
	public MedioPago getMedioPago() {
		return this.medioPago;
	}

	public void setMedioPago(MedioPago medioPago) {
		this.medioPago = medioPago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_VENTA", nullable = false, length = 7)
	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	@Column(name = "ESTADO_VENTA", nullable = false, length = 3)
	public String getEstadoVenta() {
		return this.estadoVenta;
	}

	public void setEstadoVenta(String estadoVenta) {
		this.estadoVenta = estadoVenta;
	}

	@Column(name = "VALOR_TOTAL", nullable = false, precision = 18)
	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}
        
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "venta")
	public Set<DetalleVenta> getDetalleVentas() {
		return this.detalleVentas;
	}

	public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
		this.detalleVentas = detalleVentas;
	}

    public void setCliente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
