package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Bodega generated by hbm2java
 */
public class BodegaDTO implements java.io.Serializable {

        /**
         *
         */
        private static final long serialVersionUID = 1L;
        private BigDecimal idBodega;
        private String nombreBodega;
        private String direccionBodega;
        private Set<InventarioDTO> inventarios = new HashSet<InventarioDTO>(0);

        public BodegaDTO() {
        }

        public BodegaDTO(BigDecimal idBodega, String nombreBodega, String direccionBodega) {
            this.idBodega = idBodega;
            this.nombreBodega = nombreBodega;
            this.direccionBodega = direccionBodega;
        }

        public BodegaDTO(BigDecimal idBodega, String nombreBodega, String direccionBodega, Set<InventarioDTO> inventarios) {
            this.idBodega = idBodega;
            this.nombreBodega = nombreBodega;
            this.direccionBodega = direccionBodega;
            this.inventarios = inventarios;
        }

        public BigDecimal getIdBodega() {
            return this.idBodega;
        }

        public void setIdBodega(BigDecimal idBodega) {
            this.idBodega = idBodega;
        }

        public String getNombreBodega() {
            return this.nombreBodega;
        }

        public void setNombreBodega(String nombreBodega) {
            this.nombreBodega = nombreBodega;
        }

        public String getDireccionBodega() {
            return this.direccionBodega;
        }

        public void setDireccionBodega(String direccionBodega) {
            this.direccionBodega = direccionBodega;
        }

        public Set<InventarioDTO> getInventarios() {
            return this.inventarios;
        }

        public void setInventarios(Set<InventarioDTO> inventarios) {
            this.inventarios = inventarios;
        }

}
