package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */

public class ClienteDTO implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idCliente;
	private String documento;
	private String tipoDocumento;
	private String correo;
	private String contrasena;
	private String nombresCliente;
	private String apellidosCliente;
	private String fotoCliente;
	private String telefono;
	private Character genero;
	private Date fechaNacimiento;
	private String direccionCliente;
	private Set<MedioPagoDTO> medioPagos = new HashSet<MedioPagoDTO>(0);
	private Set<VentaDTO> ventas = new HashSet<VentaDTO>(0);

	public ClienteDTO() {
	}

	public ClienteDTO(BigDecimal idCliente, String documento, String tipoDocumento, String correo, String contrasena,
			String nombresCliente, String apellidosCliente) {
		this.idCliente = idCliente;
		this.documento = documento;
		this.tipoDocumento = tipoDocumento;
		this.correo = correo;
		this.contrasena = contrasena;
		this.nombresCliente = nombresCliente;
		this.apellidosCliente = apellidosCliente;
	}

	public ClienteDTO(BigDecimal idCliente, String documento, String tipoDocumento, String correo, String contrasena,
			String nombresCliente, String apellidosCliente, String fotoCliente, String telefono, Character genero,
			Date fechaNacimiento, String direccionCliente, Set<MedioPagoDTO> medioPagos, Set<VentaDTO> ventas) {
		this.idCliente = idCliente;
		this.documento = documento;
		this.tipoDocumento = tipoDocumento;
		this.correo = correo;
		this.contrasena = contrasena;
		this.nombresCliente = nombresCliente;
		this.apellidosCliente = apellidosCliente;
		this.fotoCliente = fotoCliente;
		this.telefono = telefono;
		this.genero = genero;
		this.fechaNacimiento = fechaNacimiento;
		this.direccionCliente = direccionCliente;
		this.medioPagos = medioPagos;
		this.ventas = ventas;
	}

	public BigDecimal getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(BigDecimal idCliente) {
		this.idCliente = idCliente;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}
        
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getNombresCliente() {
		return this.nombresCliente;
	}

	public void setNombresCliente(String nombresCliente) {
		this.nombresCliente = nombresCliente;
	}

	public String getApellidosCliente() {
		return this.apellidosCliente;
	}

	public void setApellidosCliente(String apellidosCliente) {
		this.apellidosCliente = apellidosCliente;
	}

	public String getFotoCliente() {
		return this.fotoCliente;
	}

	public void setFotoCliente(String fotoCliente) {
		this.fotoCliente = fotoCliente;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Character getGenero() {
		return this.genero;
	}

	public void setGenero(Character genero) {
		this.genero = genero;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getDireccionCliente() {
		return this.direccionCliente;
	}

	public void setDireccionCliente(String direccionCliente) {
		this.direccionCliente = direccionCliente;
	}
        
	public Set<MedioPagoDTO> getMedioPagos() {
		return this.medioPagos;
	}

	public void setMedioPagos(Set<MedioPagoDTO> medioPagos) {
		this.medioPagos = medioPagos;
	}

	public Set<VentaDTO> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<VentaDTO> ventas) {
		this.ventas = ventas;
	}

}
