package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Descuento generated by hbm2java
 */


public class DescuentoDTO implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idDescuento;
	private ProductoDTO producto;
	private BigDecimal porcentaje;
	private Date fechaInicial;
	private Date fechaFinal;

	public DescuentoDTO() {
	}

	public DescuentoDTO(BigDecimal idDescuento, ProductoDTO producto, Date fechaInicial) {
		this.idDescuento = idDescuento;
		this.producto = producto;
		this.fechaInicial = fechaInicial;
	}

	public DescuentoDTO(BigDecimal idDescuento, ProductoDTO producto, BigDecimal porcentaje, Date fechaInicial,
			Date fechaFinal) {
		this.idDescuento = idDescuento;
		this.producto = producto;
		this.porcentaje = porcentaje;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
	}
	
	public BigDecimal getIdDescuento() {
		return this.idDescuento;
	}

	public void setIdDescuento(BigDecimal idDescuento) {
		this.idDescuento = idDescuento;
	}
	
	public ProductoDTO getProducto() {
		return this.producto;
	}

	public void setProducto(ProductoDTO producto) {
		this.producto = producto;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Date getFechaInicial() {
		return this.fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

}
