package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * DetalleVenta generated by hbm2java
 */

public class DetalleVentaDTO implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idDetalleVenta;
	private ProductoDTO producto;
	private VentaDTO venta;
	private BigDecimal valorUnitario;
	private BigDecimal cantidadVenta;

	public DetalleVentaDTO() {
	}

	public DetalleVentaDTO(BigDecimal idDetalleVenta, ProductoDTO producto, VentaDTO venta, BigDecimal valorUnitario,
			BigDecimal cantidadVenta) {
		this.idDetalleVenta = idDetalleVenta;
		this.producto = producto;
		this.venta = venta;
		this.valorUnitario = valorUnitario;
		this.cantidadVenta = cantidadVenta;
	}

	public BigDecimal getIdDetalleVenta() {
		return this.idDetalleVenta;
	}

	public void setIdDetalleVenta(BigDecimal idDetalleVenta) {
		this.idDetalleVenta = idDetalleVenta;
	}

	public ProductoDTO getProducto() {
		return this.producto;
	}

	public void setProducto(ProductoDTO producto) {
		this.producto = producto;
	}

	public VentaDTO getVenta() {
		return this.venta;
	}

	public void setVenta(VentaDTO venta) {
		this.venta = venta;
	}

	public BigDecimal getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public BigDecimal getCantidadVenta() {
		return this.cantidadVenta;
	}

	public void setCantidadVenta(BigDecimal cantidadVenta) {
		this.cantidadVenta = cantidadVenta;
	}

}
