package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Inventario generated by hbm2java
 */


public class InventarioDTO implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idInventario;
	private BodegaDTO bodega;
	private ProductoDTO producto;
	private BigDecimal cantidadDisponible;

	public InventarioDTO() {
	}

	public InventarioDTO(BigDecimal idInventario, BodegaDTO bodega, ProductoDTO producto, BigDecimal cantidadDisponible) {
		this.idInventario = idInventario;
		this.bodega = bodega;
		this.producto = producto;
		this.cantidadDisponible = cantidadDisponible;
	}

	public BigDecimal getIdInventario() {
		return this.idInventario;
	}

	public void setIdInventario(BigDecimal idInventario) {
		this.idInventario = idInventario;
	}
	
	public BodegaDTO getBodega() {
		return this.bodega;
	}

	public void setBodega(BodegaDTO bodega) {
		this.bodega = bodega;
	}
	
	public ProductoDTO getProducto() {
		return this.producto;
	}

	public void setProducto(ProductoDTO producto) {
		this.producto = producto;
	}

	public BigDecimal getCantidadDisponible() {
		return this.cantidadDisponible;
	}

	public void setCantidadDisponible(BigDecimal cantidadDisponible) {
		this.cantidadDisponible = cantidadDisponible;
	}

}
