package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */

public class ProductoDTO implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private BigDecimal idProducto;
	private String nombreProducto;
	private String descripcionProducto;
	private String fotoProducto;
	private String unidadMedida;
	private BigDecimal mesesGarantia;
	private String fabricante;
	private String estadoProducto;
	private BigDecimal precioMinimo;
	private Set<DetalleVentaDTO> detalleVentas = new HashSet<DetalleVentaDTO>(0);
	private Set<DescuentoDTO> descuentos = new HashSet<DescuentoDTO>(0);
	private Set<InventarioDTO> inventarios = new HashSet<InventarioDTO>(0);

	public ProductoDTO() {
	}

	public ProductoDTO(BigDecimal idProducto, String nombreProducto, String unidadMedida, String fabricante,
			String estadoProducto, BigDecimal precioMinimo) {
		this.idProducto = idProducto;
		this.nombreProducto = nombreProducto;
		this.unidadMedida = unidadMedida;
		this.fabricante = fabricante;
		this.estadoProducto = estadoProducto;
		this.precioMinimo = precioMinimo;
	}

	public ProductoDTO(BigDecimal idProducto, String nombreProducto, String descripcionProducto, String fotoProducto,
			String unidadMedida, BigDecimal mesesGarantia, String fabricante, String estadoProducto,
			BigDecimal precioMinimo, Set<DetalleVentaDTO> detalleVentas, Set<DescuentoDTO> descuentos,
			Set<InventarioDTO> inventarios) {
		this.idProducto = idProducto;
		this.nombreProducto = nombreProducto;
		this.descripcionProducto = descripcionProducto;
		this.fotoProducto = fotoProducto;
		this.unidadMedida = unidadMedida;
		this.mesesGarantia = mesesGarantia;
		this.fabricante = fabricante;
		this.estadoProducto = estadoProducto;
		this.precioMinimo = precioMinimo;
		this.detalleVentas = detalleVentas;
		this.descuentos = descuentos;
		this.inventarios = inventarios;
	}

	public BigDecimal getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(BigDecimal idProducto) {
		this.idProducto = idProducto;
	}

	public String getNombreProducto() {
		return this.nombreProducto;
	}

	public void setNombreProducto(String nombreProducto) {
		this.nombreProducto = nombreProducto;
	}

	public String getDescripcionProducto() {
		return this.descripcionProducto;
	}

	public void setDescripcionProducto(String descripcionProducto) {
		this.descripcionProducto = descripcionProducto;
	}

	public String getFotoProducto() {
		return this.fotoProducto;
	}

	public void setFotoProducto(String fotoProducto) {
		this.fotoProducto = fotoProducto;
	}

	public String getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

	public BigDecimal getMesesGarantia() {
		return this.mesesGarantia;
	}

	public void setMesesGarantia(BigDecimal mesesGarantia) {
		this.mesesGarantia = mesesGarantia;
	}

	public String getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(String fabricante) {
		this.fabricante = fabricante;
	}

	public String getEstadoProducto() {
		return this.estadoProducto;
	}

	public void setEstadoProducto(String estadoProducto) {
		this.estadoProducto = estadoProducto;
	}

	public BigDecimal getPrecioMinimo() {
		return this.precioMinimo;
	}

	public void setPrecioMinimo(BigDecimal precioMinimo) {
		this.precioMinimo = precioMinimo;
	}

	public Set<DetalleVentaDTO> getDetalleVentas() {
		return this.detalleVentas;
	}

	public void setDetalleVentas(Set<DetalleVentaDTO> detalleVentas) {
		this.detalleVentas = detalleVentas;
	}

	public Set<DescuentoDTO> getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(Set<DescuentoDTO> descuentos) {
		this.descuentos = descuentos;
	}
        
	public Set<InventarioDTO> getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set<InventarioDTO> inventarios) {
		this.inventarios = inventarios;
	}

}
