package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class ReporteDTO implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private String nombreProducto;
    private String documentoCliente;
    private String medioPago;
    private BigDecimal cantidad;
    private BigDecimal valorUnitario;
    private Date fechaVenta;

    public ReporteDTO() {
    }

    public ReporteDTO(String nombreProducto, String documentoCliente, String medioPago, BigDecimal cantidad, BigDecimal valorUnitario, Date fechaVenta) {
        this.nombreProducto = nombreProducto;
        this.documentoCliente = documentoCliente;
        this.medioPago = medioPago;
        this.cantidad = cantidad;
        this.valorUnitario = valorUnitario;
        this.fechaVenta = fechaVenta;
    }

    public String getNombreProducto() {
        return nombreProducto;
    }

    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    public String getDocumentoCliente() {
        return documentoCliente;
    }

    public void setDocumentoCliente(String documentoCliente) {
        this.documentoCliente = documentoCliente;
    }

    public String getMedioPago() {
        return medioPago;
    }

    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }

    public BigDecimal getCantidad() {
        return cantidad;
    }

    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    public BigDecimal getValorUnitario() {
        return valorUnitario;
    }

    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    public Date getFechaVenta() {
        return fechaVenta;
    }

    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

}
