package com.globalhitss.miingresohitss.dto;
// Generated 7/05/2020 10:14:05 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class VentaDTO implements java.io.Serializable {

        /**
         *
         */
        private static final long serialVersionUID = 1L;
        private BigDecimal idVenta;
        private ClienteDTO cliente;
        private MedioPagoDTO medioPago;
        private Date fechaVenta;
        private String estadoVenta;
        private BigDecimal valorTotal;
        private Set<DetalleVentaDTO> detalleVentas = new HashSet<DetalleVentaDTO>(0);

        public VentaDTO() {
        }

        public VentaDTO(BigDecimal idVenta, ClienteDTO cliente, MedioPagoDTO medioPago, Date fechaVenta, String estadoVenta,
                BigDecimal valorTotal) {
            this.idVenta = idVenta;
            this.cliente = cliente;
            this.medioPago = medioPago;
            this.fechaVenta = fechaVenta;
            this.estadoVenta = estadoVenta;
            this.valorTotal = valorTotal;
        }

        public VentaDTO(BigDecimal idVenta, ClienteDTO cliente, MedioPagoDTO medioPago, Date fechaVenta, String estadoVenta,
                BigDecimal valorTotal, Set<DetalleVentaDTO> detalleVentas) {
            this.idVenta = idVenta;
            this.cliente = cliente;
            this.medioPago = medioPago;
            this.fechaVenta = fechaVenta;
            this.estadoVenta = estadoVenta;
            this.valorTotal = valorTotal;
            this.detalleVentas = detalleVentas;
        }

        public BigDecimal getIdVenta() {
            return this.idVenta;
        }

        public void setIdVenta(BigDecimal idVenta) {
            this.idVenta = idVenta;
        }

        public ClienteDTO getCliente() {
            return this.cliente;
        }

        public void setCliente(ClienteDTO cliente) {
            this.cliente = cliente;
        }

        public MedioPagoDTO getMedioPago() {
            return this.medioPago;
        }

        public void setMedioPago(MedioPagoDTO medioPago) {
            this.medioPago = medioPago;
        }

        public Date getFechaVenta() {
            return this.fechaVenta;
        }

        public void setFechaVenta(Date fechaVenta) {
            this.fechaVenta = fechaVenta;
        }

        public String getEstadoVenta() {
            return this.estadoVenta;
        }

        public void setEstadoVenta(String estadoVenta) {
            this.estadoVenta = estadoVenta;
        }

        public BigDecimal getValorTotal() {
            return this.valorTotal;
        }

        public void setValorTotal(BigDecimal valorTotal) {
            this.valorTotal = valorTotal;
        }

        public Set<DetalleVentaDTO> getDetalleVentas() {
            return this.detalleVentas;
        }

        public void setDetalleVentas(Set<DetalleVentaDTO> detalleVentas) {
            this.detalleVentas = detalleVentas;
        }

}
